format:
  revealjs:
    smaller: true
    theme: [default, edtheme.scss]
slide-number: true
progress: false
title-slide-attributes:
  data-background-color: "#041E42"
  data-color: "#d6d6d6"
logo: img/white_logo.png
