---
title: "Integration"
answers: false  # toggle true/false to show solutions
number-sections: true
---

Remember the advice from week 1: if there's any particular question you find difficult, try using [ELM](https://elm.edina.ac.uk/elm/elm) to create some similar questions to practice with before moving on to harder questions.

## Integrals

1. Find $\int f(x)~\text{d}x$ when $f(x) = x^2$, $f(x) = 3$, and $f(x) = x^3 + 3x^2 + 3x + 1$.

2. Find the area under the previous curves between $0$ and $1$.

3. Find $\int f(t)~\text{d}t$ when $f(t) = 2e^{2t}$, $f(t) = 2\cos(2t)$, and $f(t) = 1/\cos^2(t)$.

## Using Parts

The integration by parts formula,
$$
  \int u(x)v'(x)~\text{d}x = u(x)v(x) - \int u'(x)v(x)~\text{d}x,
$$
gives us a way to break down complicated integrals that involve products.

1. Find $I = \int xe^x~\text{d}x.$

2. Find $I_2 = \int x^2 e^x~\text{d}x.$

3. Find $I_3 = \int x^3 e^x~\text{d}x.$

4. Is there a formula for $I_n = \int x^n e^x~\text{d}x$, where $n$ is a strictly positive integer?

## Areas

A shape $D_n$ is defined as the space enclosed by the four line segments
\begin{equation*}
  \begin{matrix}
    y = h\left(x-b\right)^n,\ 0\leq x \leq b  & \quad & y = h\left(x+b\right)^n,\ -b\leq x\leq 0 \\
    y = -h\left(x+b\right)^n,\ -b\leq x\leq 0 & \quad & y = -h\left(x-b\right)^n,\ 0\leq x\leq b
  \end{matrix}
\end{equation*}
where $b$ and $h$ are positive real numbers and $n$ is a positive integer.

1. What is the area of $D_1$?

:::{.callout-note title=Hint}
What does $D_1$ look like?
:::

2. What is the area of $D_2$?

3. What role do the domains of $b$, $h$, and $n$ play?
