---
title: "Differentiation"
answers: false  # toggle true/false to show solutions
number-sections: true
---

This week uses calculus to explore the properties different models. Once you've worked out an answer, you should check it against a scientific calculator, [algebra software](https://www.wolframalpha.com/), or [graphing software](https://www.geogebra.org/calculator/).

## Derivatives

Before we look at applications, here are some starter questions to practice differentiating.

1. Find $f'(x)$ when $f(x) = x^2$, $f(x) = 3$, and $f(x) = x^3 + 3x^2 + 3x + 1$.

2. Use two different methods to show $\frac{\text{d}}{\text{d}x}\big((x+a)(x-a)\big) = 2x$ for all $a\in\mathbb{R}$.

3. Find $\dot{x}$ when $x = e^{2t}$, $x = \sin(2t)$, and $x = \tan(t)$.

## Model Interpretations

In workshop two we looked at a range of different models for real-world phenomena. For each of these, use software to find the derivative of the model with respect to the independent variable. Then, examine it graphically and describe the meaning of the derivative in context.

1. Compound interest, modelled by $P(t) = Q e^{rt}$, where $Q$ is the initial investment and $r$ is the rate of interest.

2. Population growth, modelled by $P(t) = \frac{P_0 \cdot K}{P_0 + (K - P_0)e^{-rt}}$, with initial population size $P_0$, a growth rate $r$ per day, and a maximum feasible population size $K$.

3. Sound in decibels, modelled by $d(p) = 10\log\left(\frac{p}{p_{0}}\right)$, where $p_0$ is intensity of the faintest audible sound.

## Optimization

We discussed how one of the key applications of differentiation is to find the maximum or minimum value a model can take. These points happen when the gradient is zero.

1. What point is the minimum of $f(x) = \frac{x(x+1)}{2}$?

2. Does this minimum have meaning in the context of $S_n$ from the last workshop?

3. Could this be used to make a better argument that $\sum_{n=1}^{\infty} n \neq -\frac{1}{12}$?

## Classifying Derivatives

It's not always so clear whether a critical point is a maximum, minimum, or an inflection. To check this we look at the second derivative: $\frac{\text{d}^2}{\text{d}x^2}$, $f''(x)$, or $\ddot{x}$.

At a point $x$ where $f'(x) = 0$:

- If $f''(x) > 0$, then $x$ is a local minimum,
- If $f''(x) < 0$, then $x$ is a local maximum,
- If $f''(x) = 0$, more information is needed.

This is sometimes called the **derivative test**.

1. Verify that $(-0.5, -0.125)$ is a minimum of $f(x) = \frac{x(x+1)}{2}$.

2. Classify the critical points of $f(x) = x^3 + 3x^2 - 6x - 8$.

3. Find the time at which the population $P(t)$ is changing fastest.

:::{.callout-note title=Hint}
If $f(x) = \frac{f_1(x)}{f_2(x)}$, when is $f(x) = 0$?
:::
