format:
  html:
    number-sections: true
    include-in-header:
      - text: "<style>
            /* make sure figure captions are always centred */
            p.caption, figcaption {
              margin: auto;
              text-align: center;
            }
          </style>"
